RECOVERY SPRINT 3
team-goofy/project-train-game pull request #55
Opened 2023-06-13 15:17 UTC by KONRADS098

[RECOVERY SPRINT 3](https://trello.com/c/1vY5RsXZ/85-recovery-sprint-3)

2023-06-16 12:28 UTC, mandylbbh requested changes

2023-06-16 12:28 UTC, mandylbbh commented on client/src/app/game-page/src/lib/random-train/random-train.component.html
is de tekst kleiner ivm mobile? Na sprint 2 kregen we nml de feedback dat de pagina niet helemaal duidelijk was, nu heb ik het idee dat exit train at ook weer wat meer wegvalt.

Misschien de tekst: Exit the train at station: zo laten
en dan het station zelf zwart ipv grijs

2023-06-16 12:28 UTC, mandylbbh commented on client/src/app/game-page/src/lib/random-train/random-train.component.html
Op een gegeven moment blijft de pagina laden, hier krijgt de user geen feedback wat er is en kan alleen terug. Is dit omdat er geen treinen meer gevonden worden? Want dan kan er beter de vorige error message in beeld komen

![image](https://github.com/team-goofy/project-train-game/assets/46960483/42ad5a49-6db2-46ca-8634-1205779825ee)

2023-06-16 12:28 UTC, mandylbbh commented on client/src/app/game-page/src/lib/picture-upload-page/picture-upload-page.component.scss
![image](https://github.com/team-goofy/project-train-game/assets/46960483/81f608b7-a2b2-4305-b3c0-a66b3c0a0620)
 spreekt voor zich

2023-06-16 13:24 UTC, mandylbbh commented on client/src/app/game-page/src/lib/random-train/random-train.component.html
-> loader is top verder, zou dit ook kunnen als je op refetch klikt bij locatie zoeken?

2023-06-19 08:17 UTC, HHK3 approved these changes

2023-06-19 08:17 UTC, mandylbbh approved these changes

2023-06-19 08:17 UTC, merged